<?php
$lead_pending = get_user_meta(get_current_user_id(), 'lead_pending', true) ?: 0;
$lead_booked = get_user_meta(get_current_user_id(), 'lead_booked', true) ?: 0;
$lead_confirmed = get_user_meta(get_current_user_id(), 'lead_confirmed', true) ?: 0;
$lead_completed = get_user_meta(get_current_user_id(), 'lead_completed', true) ?: 0;

$data = [
    ['label' => 'Pending', 'value' => $lead_pending],
    ['label' => 'Booked', 'value' => $lead_booked],
    ['label' => 'Confirmed', 'value' => $lead_confirmed],
    ['label' => 'Completed', 'value' => $lead_completed],
];

$customer_invite_code = get_user_meta(get_current_user_id(), 'customer_invite_code', true);
$customers = get_customers_by_linked_code($customer_invite_code);

$user = wp_get_current_user();
$user_name = $user->display_name;
$user_email = $user->user_email;
$user_first_name = get_user_meta($user->ID, 'first_name', true);
$user_last_name = get_user_meta($user->ID, 'last_name', true);
$user_full_name = $user_first_name . ' ' . $user_last_name;

$all_zero = array_reduce($data, function ($carry, $item) {
    return $carry && ($item['value'] == 0);
}, true);

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lead Statistics Report</title>
    <style>
        body {
            font-family: "Times New Roman", sans-serif;
            background-color: #F6F9FA;
        }

        .lead-template-wrapper {
            margin: 20px;
        }

        .title {
            font-family: "Times New Roman", sans-serif;
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 20px;
        }

        .subtitle {
            font-family: "Times New Roman", sans-serif;
            font-size: 18px;
            font-weight: bold;
            margin-top: 20px;
            margin-bottom: 10px;
        }

        .description {
            font-family: "Times New Roman", sans-serif;
            font-size: 14px;
            margin-bottom: 20px;
        }

        .alert {
            font-weight: bold;
            color: #EC7979;
        }

        .label {
            font-family: "Times New Roman", sans-serif;
            font-size: 14px;
        }

        .body {
            font-family: "Times New Roman", sans-serif;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table,
        th,
        td {
            border: 1px solid black;
        }

        th,
        td {
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

<body>
    </header>
    <div class="lead-template-wrapper">
        <div class="title">Lead Statistics Report</div>
        <div class="description">This report provides an overview of your lead statistics, including a pie chart representation and detailed tables of your leads and customers linked to your invite code.</div>

        <!-- Report Generated By -->
        <div class="subtitle">Report Generated By</div>
        <div class="description">
            <strong>Name:</strong> <?= htmlspecialchars($user_full_name) ?><br>
            <strong>Email:</strong> <?= htmlspecialchars($user_email) ?>
        </div>

        <!-- Pie Chart -->
        <div class="subtitle">Pie Chart</div>
        <div class="description">The pie chart below shows the distribution of your leads across different statuses.</div>
        <?php if ($all_zero): ?>
            <div class="description alert">No customers found!</div>
        <?php else: ?>
            
        <?php endif; ?>

        <!-- Leads Summary Table -->
        <div class="subtitle">Leads Summary</div>
        <div class="description">The table below provides a detailed summary of your leads, categorized by their status.</div>
        <table class="body">
            <tr>
                <th>Status</th>
                <th>Value</th>
            </tr>
            <?php foreach ($data as $row): ?>
                <tr>
                    <td><?= htmlspecialchars($row['label']) ?></td>
                    <td><?= htmlspecialchars($row['value']) ?: 0 ?></td>
                </tr>
            <?php endforeach; ?>
        </table>

        <!-- Customers Table -->
        <div class="subtitle">Your Leads</div>
        <div class="description">The table below lists all customers linked to your invite code, along with their details.</div>
        <table>
            <tr>
                <th>User ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>State</th>
                <th>City</th>
                <th>Status</th>
            </tr>
            <?php if (!empty($customers)) : ?>
                <?php foreach ($customers as $customer) : ?>
                    <tr>
                        <td><?= htmlspecialchars($customer['user_id']) ?></td>
                        <td><?= htmlspecialchars($customer['first_name']) ?></td>
                        <td><?= htmlspecialchars($customer['last_name']) ?></td>
                        <td><?= htmlspecialchars($customer['state']) ?></td>
                        <td><?= htmlspecialchars($customer['city']) ?></td>
                        <td><?= htmlspecialchars($customer['status']) ?: 0 ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else : ?>
                <tr>
                    <td colspan="4" class="alert">No customers found!</td>
                </tr>
            <?php endif; ?>
        </table>
    </div>
</body>

</html>